"""
pipeline/thumbnail_maker.py
Generates eye-catching, high-CTR YouTube thumbnails (1280×720).
Uses Pillow to draw clean gradient backgrounds, geometric accent shapes,
channel branding (logo placeholder), and high-contrast bold typography.
"""

import logging
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

from pipeline.config import (
    OUTPUT_DIR, FONTS_DIR, THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT,
    COLOR_DARK, COLOR_PRIMARY, COLOR_ACCENT, COLOR_WHITE
)

logger = logging.getLogger(__name__)


def _draw_gradient(draw: ImageDraw.ImageDraw, width: int, height: int, start_color: tuple, end_color: tuple) -> None:
    """Draw a smooth diagonal background gradient."""
    for y in range(height):
        # Calculate interpolation factor
        ratio = y / height
        r = int(start_color[0] * (1 - ratio) + end_color[0] * ratio)
        g = int(start_color[1] * (1 - ratio) + end_color[1] * ratio)
        b = int(start_color[2] * (1 - ratio) + end_color[2] * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))


def generate_thumbnail(text: str, output_filename: str = "thumbnail.jpg") -> Path:
    """
    Programmatically generates a premium high-contrast thumbnail.

    Args:
        text: Punchy text overlay (usually generated by GPT, <= 6 words)
        output_filename: File name for saving

    Returns:
        Path to the saved thumbnail image file
    """
    output_path = OUTPUT_DIR / output_filename
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Base Image with diagonal dark-blue/dark-grey gradient
    img = Image.new("RGB", (THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT), color=COLOR_DARK)
    draw = ImageDraw.Draw(img)
    
    # Draw dark diagonal background gradient
    start_rgb = (10, 10, 25)
    end_rgb = (5, 5, 8)
    _draw_gradient(draw, THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT, start_rgb, end_rgb)

    # 2. Add abstract geometric accent shapes for premium look
    # Draw a futuristic neon cyan accent line/polygon on the left
    draw.polygon(
        [(0, 0), (80, 0), (20, THUMBNAIL_HEIGHT), (0, THUMBNAIL_HEIGHT)],
        fill=COLOR_PRIMARY
    )
    # Highlight triangle at the bottom right
    draw.polygon(
        [(THUMBNAIL_WIDTH - 150, THUMBNAIL_HEIGHT), (THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT - 100), (THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT)],
        fill=COLOR_ACCENT
    )

    # 3. Text rendering preparation
    # Try loading bold brand font (Montserrat)
    font_path = FONTS_DIR / "Montserrat-Bold.ttf"
    font_size = 76
    try:
        if font_path.exists():
            font = ImageFont.truetype(str(font_path), font_size)
        else:
            font = ImageFont.load_default()
            logger.warning("Montserrat-Bold font not found. Using PIL default.")
    except Exception as e:
        logger.warning(f"Error loading font: {e}. Using default.")
        font = ImageFont.load_default()

    # Clean text and split to fit nicely
    words = text.upper().split()
    lines = []
    current_line = []
    
    # Simple automatic line wrapper for thumbnail text
    for word in words:
        current_line.append(word)
        test_line = " ".join(current_line)
        bbox = draw.textbbox((0, 0), test_line, font=font)
        w = bbox[2] - bbox[0]
        if w > THUMBNAIL_WIDTH * 0.75: # Occupy up to 75% width
            current_line.pop()
            lines.append(" ".join(current_line))
            current_line = [word]
    if current_line:
        lines.append(" ".join(current_line))

    # Limit to maximum 3 lines for clean presentation
    lines = lines[:3]

    # Calculate overall vertical offset to center lines
    line_heights = []
    total_text_height = 0
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=font)
        h = bbox[3] - bbox[1]
        line_heights.append(h)
        total_text_height += h + 20
        
    y = (THUMBNAIL_HEIGHT - total_text_height) // 2

    # 4. Draw text with thick drop shadows / strokes
    for i, line in enumerate(lines):
        bbox = draw.textbbox((0, 0), line, font=font)
        w = bbox[2] - bbox[0]
        h = line_heights[i]
        
        # Center horizontally on the right portion of thumbnail
        x = 120 + ((THUMBNAIL_WIDTH - 200 - w) // 2)
        
        # Outer thick stroke shadow (black outline)
        stroke_w = 6
        for offset_x in range(-stroke_w, stroke_w + 1):
            for offset_y in range(-stroke_w, stroke_w + 1):
                if offset_x**2 + offset_y**2 <= stroke_w**2:
                    draw.text((x + offset_x, y + offset_y), line, font=font, fill="#000000")

        # Select color (Alternate color for emphasis on middle line)
        text_color = COLOR_ACCENT if i == 1 else COLOR_WHITE
        if len(lines) == 1:
            text_color = COLOR_PRIMARY
            
        # Draw main text overlay
        draw.text((x, y), line, font=font, fill=text_color)
        y += h + 20

    # 5. Save output JPEG
    img.save(output_path, "JPEG", quality=95)
    logger.info(f"Thumbnail created successfully at: {output_path}")
    return output_path


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    p = generate_thumbnail("SECRET CHATGPT RESUME HACK")
    print(f"Thumbnail saved to: {p}")
